language: java
install: true
script: bash src/main/scripts/travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis[0-9]+$/
env:
  global:
  - ATOMIST_REPO_USER=travis-mvn-deploy
  - secure: D0urzio/o3GwpHgV7GRcPOwrxCV8dQ4WulEMwLwTLbki82YD2KJP9xR2qjwmk1rcBe43nKM8tziSJNjojjs0YKxPeUUwmXGisq842a1V0W9tHVLSkb0Ylt3tI3hlHonXt3mIu8ixqF7JDKKpOEJImBJRkapcLs+Gt4g5W6gLYkkQ5qFo+JHNGdIYt49YW3MAhujYX8RGSF8N4DAv2go2duSBAzfpbW4jUq/tl4qqz/5mcN0FRTvtwPk/yLIO5f5MfOOREvmBVz6vBGlT7PFJeCCQoNhnXMb9UOuIadPsuuxD2VMu6khnuI0DIZsbqRs6sGomPJ291SXUZWPO7wa0vmm8hiYQlWlBAEEfld7hj2uWjldgytlB/T2GCW5t5OaAncEVdKBPoNhXp5U+tp30t8Goed2IUFNNGRQ8VIq6qdmJ0qDsX7WvhqBHnmxR4lg2gvF+GBeJmlxnkc93CssfrO1bUlBsezeFM6lDVPhYfhfluVw9ObPmLpsAnqyCu3+wOE17tljlHps651yzO63yeWXoPkhPCreLiHkwy/P6RJBFDCqqNHrjOgj9H16oDLIUjo7Mlvr4sszfxdJdEOwinsC3eeM3hF9acJ+9v33/xZ9OCeW5lvcSCLMNSlX4vBJtZo2C/UMtf2bNNm7klfKYD8CGuOEn7F7a/XOzQ/HJBvI=
  - ARTIFACTORY_USER=travis-mvn-deploy
  - secure: jA7UIgyttFR5qC+G9bivgFq6zty5Z/grkmHVyuLFNfT7DV1I2xHkWwUuwxQggMUT/mx9G7BcViuOHE0MvTzuni1z/pWPZUe7psD966NQzToHW/ut3KP2/3m707rn+nSPo9l/h8WuYlVUqbhsRB1zhR3ZYVfkrOALfsMNAE8jBuS42C3opiApmTgNqHx9H+dZaoWA3vWAY75oLw8D2Vp3bJL2qdluBDguxh0KaDzSwhVGJ9h/JyHMjk0ZTiMePagJwzyVN0hQqkxqpr4JKXnbI4PE8/pKWJvVH+gOwd5J68McRPnm8FRLPCRDzxKqPHWvkvU9oUtL7Tzk5UocM4MrECnzU+aNhYxohH+M1Yu5e2YPNXJhQ6+p6BKWwmZv1RKlYdXBcLsgoYVHwTWahczSUT9/ay0D2ugiKy0AA6Hu7cDbegQpiBCU6AKgUqMIlAj6CJtcLBqLE/qOXv2AcWbDNIR5p2QXQfTErV6Y8LR6IXDWKyPgUu36JICJNSjps6drUzCNFy8t1EYxzmtmDtQ3Nkyc0siw+p56N8g0OMECqAR0YdQ0nRVDRO5P7ShwjlmQCb14iSJz8nOWHEfI3ThcXZa9Jvk8oYvwsc6h+QFaqUmDEQIvhxLcBnTLn+VegyXDnr7HcYA4CxPfZj+6fmb5brgAtfGWJ9Nf/72v3chZ03o=
  - HOMEBREW_TAP=atomist/homebrew-tap
  - secure: h4NRlGqGoORe/Idtgg5/2UBmKhKIznXe8LjpRkN7cce2sWzEMm1fJ6li2iJ8f7bayuBtoeuW/bcd/QpG9t/l4ckNM/inUQFoLKQUqrvbqq1W2KDVnRRo6e8vssUVNVGL1wjxQM80IlQGEZEL+B34AV54FLQhXe8MeYmbAHt+ruKO6HC8zTqy0KB0pr+oi4/U51DRAxegCaFDxn0Vhu1B4dTyKyjMcswKt030DjT77jxnAgoJgMFd+w8QAqYlhk6MvVX/ZZ+CO43JBWt7nSMuiweegw7+XKkFMzX6T/CV4oimi5pc+XZLez4vlRsf5UoDzh5VM4Ut0dOGoKBI5VjFirmrqDk+97jI9yLjeVJafk3RVsst9hRiyiALIr27k4CqD+hnv8Nmk8Kk+Q28XxHib+5xL4h+207ixXiD69ZEK2QiyR65ZpjsRezCwdhNXdN0Es8j3Vfao5tZfJS8/73LzA3xSRLwOeloJbEJAo3Nxrm5tOjdbT4QmpK8g9dQwAHTB7uxIz4KznzdGwAmjXBFjP8xGGVl6CHGiq7pT9Xxu1juNc7aXM7+LpONN3oJGPUXoScseT/kWl2UHkbRzyFRiXD/QPy8lK9MVpUxQlDFboTrL1b0oaBrQ5rfmiVtXVzYHPi/9FPKZ3xZCpo9vCvZj7pHJioJMu0r4Ntwx2JUg6U=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
  - $HOME/.atomist
deploy:
  provider: releases
  api_key:
    secure: BlS8PX55cPrS3zeh2DvwgHKBkLkqyk17mRDiAdTXAlPKpkV2XCY9/K0A1Jdd+6mWAygDaS3SJX5sF6dJIW/YKUNwVGl4bX4aPwGKzTjhMP/u8xf1L6KKZaNz8BDmDe/x2Qmf/KpxeGgIlexBU8+4jd5wHoUDmJzNu0gcAbmJsckwBUa4F1xo2ngnQ1EeNwFhNldh2+GQwfQrXSm6DnLeY/3pwW2Y1ap+lW/VTEfpzf4EDTeWNdnf9obijCFhIunkR4tr7VWnZwwIRRRCBhXZhcErns0/riJgCTzX+Q/nBb/NzjFMCRXT1TH4cK2G+O8oRIuHULF6ybEg13roCZNPTbCNLDcZRCGwGZPKWZxlrd2F6JkHO4nrqzJADkOMu9ApCgsScDixkskYkHCRoM58cM4Wcx/ya4zRn7/ttM/Iin2uoFJUw+0s37jwhNez8m6Vw/o+VPOjGW5tF505VCIg35Q8BzpfcbzO4Mdk2U/CYUH4Kh12pnkrHCWRaAjRG+QskVkOCPRI0RnZSMW01rxfCdRMDzlfiYtJuRTdi0ZXOZVXnANJHL4CvhutuhRCm/N2l4SDcKBlIK+rnesRHXrTYKaAAUtkgi9OoVdVX/sjf9QrW/0eDXIJJcVS1X/dUcmbNDIM6eA+OlasctiuDTF/ulLVyWDKHKg9RbWTV0BtFEQ=
  file:
  - target/rug-cli-$TRAVIS_TAG-bin.tar.gz
  - target/rug-cli-$TRAVIS_TAG-bin.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
after_deploy:
- bash src/main/scripts/update-brew.bash $HOMEBREW_TAP $GITHUB_TOKEN
- bash src/main/scripts/update-brew.bash atomisthq/s3-images $GITHUB_TOKEN images/Formula
- bash build/deb-package.bash
- bash build/rpm-package.bash
