language: java
install: true
script: bash src/main/scripts/travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: inokIUMqhIbbeD2iZbWcFiQtdTBE4bDxpOpIbNF0Xhhngj1rrES5EP79S7Yel6I5h5a6XmZhFW7I/jFNYgl6PSdncegw++vBeUtGuPV2Sr5lQHbtY2nbZ0VYJNEQF47EfrqNnOzXycAVP0ifzYJhA2tkgBClZxS0zYu42p7pMB+8DVNYG3m3l1cRAnkQ63IepFxDINV3jusrYxp2EZVBQ9JEHffFA08dI9LTIYVwT/fsoOJE3nvkvWV6A21htEy4buvrwVHkYoUTMhgIlKvaAdXFWFUvjsfp5bKKRpLtf+n3m0McmU4EWIi1tSqX4bg3EC2givRa2gCt/LaUda1fYu0YCuWtWqMsf5RvMSFjqZlnSRAeDNv5H9xQs3vatCN7fizuXQZkO0IkqSvrZpvjZ9JBamwE6FZw77OdIh+DXu/Kz0g+MegkRVaFNJuPvb/ZrfY0pO5bISh/dBuZ3RvSQNPXXBpQ0j+9qfI5ojNFgMpVptygzzfXWBXA5+5S8R1/+JhxLDpbcOa53oOcsfNn0/iAONfZ354oEFAKpvFseZ/qbIBnSBtKHCJLOYEpRcCHYdGoQUDNVFF1YFEGrEsGDJ4T0/Ya+qyYmw8QJZOG7xe2do+5Z6F3Rr9n9tc6pSBAmwIjj8Zy1v2Ju7wOpz5z0QLj/XXWIETlfhQdBu2ObL0=
  - secure: Q7r5ixdPcGkPHU5UrtuGRv5+Rv2chiJbO8ZhCLxz2RC5JR15Qxs5yKe3sYq0KZ6C2K7D6bTVAuC2CROb3Q+mzoO2Deqbvw8qBMYDsAw3rfp+Dt8K8Y379vXcDx3TzhGx7s4c1vca3NE15FkGMRBM06KKSQL4m+r6YQC3M/vu6yqm8B6CRH4csPB1s+dZAviX1QHgyMtlGlmRbt5+d0+NXjJLle1rBV9PBvaxmuaJzApfaC/hLwkqqNQYpbokhpbwqjOQxjk8B885zk1k+hfYNwdUg/hXwzD7hfJroS1KoQNEZoG4n6rjkmljn+iOQy7pnYTRL3vfN3tQJZOj7FQB9KvwgLLD9A57DzEmi0YUrFoQomM8jHUdw7y+1YjnwHInMC5TpI7ne7GeM3gQtH5qDJTfHbOmgPRs/+dS3ZMjET6WXiRVkwr7785tjDxSCM3mBtEMPqHq22BZPKp+KiUbvx2V9lgmsiwJv11fPlTzog1+/0QsjMN3yd/4qo5mN3cjDvMX/XPO5MNjPOjhA2biyhkAa2f4rO559vKu3HtPV0AHSP8QAFo2zv+4ZorpokThf+dmP3q8HNIjlkTNL1sB98qqNrVlRcJhsAsrX1paGHaNzYXQKQwtWBzrS8v2udkOIJNXtfVqVnaQ/Blcn2QL13IWFGtRmwhkC8RM8xAYR9g=
  - HOMEBREW_TAP=atomist/homebrew-tap
  - secure: lnjWsi+yS+HlI+gF/Ja3OvWQm9gA8s3AQGrZTJZ4+6qThqKSN2QVH6MEU10Ysdi+xfaSJM3ZKUFcPBplWyXvbaZn7FhRY+sRG/yAjwc/V1QE1Fpylm4D68TFtqey8yHKoNyCIpgd1THflNvzN4/t6sC4cg5Z9CXMxYnHolKzDZeGEOQZEDO/ohOJaw7gqXug2n0mmhbjhGz1ODKjFMgWwdGGLC4DUOJMMy9JfEOt6Ecu3hB8NtROr9lW/QewLJhVYC5pBxYRedHM5ToMeVS4fPRW0A13jJGpsLZLCBUpcOqGgGdK99RrdD6bXykDgF+l9JRxzjvT0ccrFx/CmjPF+P1g22pbabuHEZtyb5xBT535iQCA4D6+8eTSCkhDqKLZo84Fb7YSY8+sCSr+ZiiTEZxCAsr6gfZ8RZsGvX0kTuWBPn+gPk0OJtNQvM7aND1DHv+2Y+nV5kFV6fy2YkXgu9XorF1L0ZVV6e90p9RRpGKItbIa1MP1/NptmJV1eyXDSQgoSjbJ1GCKrwcu1ZD736VtMFKMMIp4ft/xLA0pWhrd8Mmhe3pnN6Pca/nkvt8Qu/EUplRamD8LY/y9rARvVO5Z7lZSADiuyjI+ngS+1z7uMrLTgI0GaNYDiEXBJNwnOOO0+MCuHuIvKOePhM7//+kizP6jlZOYHYGUtjy7g/M=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
  - $HOME/.atomist
deploy:
  provider: releases
  api_key:
    secure: HGg4/xb68bXhhu6Fp3obFzjG3Kk7cDr8/wKOqBbuYK5zMiq/TXSIObcxGx60GLWOjxF3DKpubWdLkwWy+Fgks1bU32uZEFijMiRGJI2Oj9qFOsg1Df3HkaLbqTvrc6zOIlnAt/INQiUKGytZ/aW7k51gneE4fORn7nFkdtAxwu0Iwev3YcwOpg3DrLA/8sNjEbDfPAibOjb0b9i4e+n9aw6KUSnmWvkaUTRu3DdUVBfHmwtAqTfNRw3g8WJRQ26d7eG4bqKrOVmUNfGGUU9HdkBXX2+Kga36zRksaWliRaOWCXCADQL6bl1QroTMZj1ltOwwWWji5WaP6NYoNohVCanlMQ07QnKNX1hPRx8A9r1hHQ0jPYDjPkayNRAwkebNcJ63LulkQPf34WeXqOjerBPNaiU1crCW2i4g4e//EHjVvdf+ZM9YBGCD14pwo4NzEthystZEzjAHsC3czaqcJpaS2rRPSHez+RQbmRPK81E4461PIAF0vLBtK8a3uVPC7zE5P+vBy0XDrBcu1BR/FfSoepm6n9Zrai/I5Qk2uBhmK30wSllme9lvFshqqQ0fSX7nHV+zoiXRQNLCrfJzyr95Awi/QpK1HyBG27kdNU6Mz7BIH36W1iWb5F7lTErLhDSurYx0jry61hktMsa0lhuKL0S+xTQcw9ICy5IyE28=
  file:
  - target/rug-cli-$TRAVIS_TAG-bin.tar.gz
  - target/rug-cli-$TRAVIS_TAG-bin.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
after_deploy:
- bash src/main/scripts/update-brew.bash $HOMEBREW_TAP $GITHUB_TOKEN
- bash src/main/scripts/update-brew.bash atomisthq/s3-images $GITHUB_TOKEN images/Formula
- bash src/main/scripts/deb-package.bash
- bash src/main/scripts/rpm-package.bash
