// Generated by Rug to TypeScript transpiler.

import { EditProject } from '@atomist/rug/operations/ProjectEditor'
import { PathExpressionEngine } from '@atomist/rug/tree/PathExpression'
import { Editor, Tags, Parameter } from '@atomist/rug/operations/Decorators'
import { Pattern } from '@atomist/rug/operations/RugOperation'
import { Project } from '@atomist/rug/model/Core'

/**
    AddReadme
    adds a project specific README
 */
@Editor("AddReadme", "adds a project specific README")
@Tags("readme", "documentation")
class AddReadme implements EditProject {

    @Parameter({
        displayName: "Project Name",
        description: "Name of the project",
        pattern: Pattern.project_name,
        validInput: "A valid GitHub project name using only letters, digits, hyphens",
        minLength: 1
    })
    project_name: string

    @Parameter({
        displayName: "Project Description",
        description: "One-sentence description of the project",
        pattern: "^.*$",
        validInput: "A string 1-90 characters long",
        minLength: 1,
        maxLength: 90
    })
    description: string

    edit(project: Project) {
        let eng: PathExpressionEngine = project.context.pathExpressionEngine
        let readme = "README.md.mustache"
        let readmeFilename = "README.md"
        let p = project

        p.merge(readme, readmeFilename, {project_name: this.project_name, description: this.description})
    }
}
export let editor_addReadme = new AddReadme();