// Generated by Rug to TypeScript transpiler.

import { EditProject } from '@atomist/rug/operations/ProjectEditor'
import { PathExpressionEngine } from '@atomist/rug/tree/PathExpression'
import { Editor, Tags, Parameter } from '@atomist/rug/operations/Decorators'
import { Pattern } from '@atomist/rug/operations/RugOperation'
import { Project } from '@atomist/rug/model/Core'

/**
    RemoveApacheSoftwareLicense20
    removes an Apache Software License version 2.0 file if present
 */
@Editor("RemoveApacheSoftwareLicense20", "removes an Apache Software License version 2.0 file if present")
@Tags("apache", "license", "documentation")
class RemoveApacheSoftwareLicense20 implements EditProject {

    edit(project: Project) {
        let licenseFilename = "LICENSE"
        let p = project

        if (p.fileExists(licenseFilename) && p.fileContains(licenseFilename, "Version 2.0")) {
            p.deleteFile(licenseFilename)
        }
    }
}
export let editor_removeApacheSoftwareLicense20 = new RemoveApacheSoftwareLicense20();