// Generated by Rug to TypeScript transpiler.

import { EditProject } from '@atomist/rug/operations/ProjectEditor'
import { PathExpressionEngine } from '@atomist/rug/tree/PathExpression'
import { Editor, Tags, Parameter } from '@atomist/rug/operations/Decorators'
import { Pattern } from '@atomist/rug/operations/RugOperation'
import { Project } from '@atomist/rug/model/Core'

/**
    RemoveCodeOfConduct
    removes CODE_OF_CONDUCT file if present
 */
@Editor("RemoveCodeOfConduct", "removes CODE_OF_CONDUCT file if present")
@Tags("documentation")
class RemoveCodeOfConduct implements EditProject {

    edit(project: Project) {
        let filename = "CODE_OF_CONDUCT.md"
        let p = project

        if (p.fileExists(filename)) {
            p.deleteFile(filename)
        }
    }
}
export let editor_removeCodeOfConduct = new RemoveCodeOfConduct();