/*
    Generated by Atomist on 25 07 2016 
*/
package com.atomist.springrest;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for SpringRest.
* Don't even think of using XML.
*/
@Configuration
public class SpringRestConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
