/*
    Generated by Atomist on 25 07 2016 
*/
package com.atomist.springrest;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringRestApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringRestApplication.class, args);
    }

    public static void main1(String[] args) {
        SpringApplication.run(SpringRestApplication.class, args);
    }

    public static void main2(String[] args) {
        SpringApplication.run(SpringRestApplication.class, args);
    }
}
